# Generated by Django 2.0.1 on 2018-03-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shopContact',
            field=models.CharField(default='99999', max_length=30),
        ),
        migrations.AddField(
            model_name='shop',
            name='shopOwner',
            field=models.CharField(default='OwnerName', max_length=30),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopName',
            field=models.CharField(default='ShopName', max_length=30),
        ),
    ]
